//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnSnyderFinalPrject.MVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatID
    {
        public int SeatID1 { get; set; }
        public int TMID { get; set; }
        public int TicketID { get; set; }
    
        public virtual TheaterMovy TheaterMovy { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
